name: Publish Schema for Bigquery

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
       
    - name: create credentials file
      run: echo '${{secrets.GOOGLE_CLOUD_CREDENTIALS}}' > ./credentials.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade google-cloud-bigquery
    - name: Publish
      env:
        GOOGLE_APPLICATION_CREDENTIALS: "./credentials.json"
      run: |
        python --version
        python ./.github/workflows/deploy.py